# TODO: integrate code coverage

branches:
  only:
    - master

language: cpp

compiler: g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - g++-7
      - libboost-graph-dev
      - liblua5.2-dev

script:
  - cd debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make all
  - make test
