language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler:
        - g++
      addons:
        apt:
          packages:
            - liblua5.2-dev
            - python3-pytest
            - valgrind

    - os: linux
      dist: bionic
      compiler:
        - g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - liblua5.2-dev
            - python3-pytest
            - valgrind
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      dist: bionic
      compiler:
        - g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - liblua5.2-dev
            - python3-pytest
            - valgrind
      env:
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      dist: bionic
      compiler:
        - g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - liblua5.2-dev
            - python3-pytest
            - valgrind
            - doxygen
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
         - DEPLOY=Yes

before_install:
  - sudo add-apt-repository -y ppa:mhier/libboost-latest
  - sudo apt-get -q update
  - sudo apt-get -y install libboost1.70-dev
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DPYTHON_BINDINGS=ON -DPYTHON_EXECUTABLE=$(which python3) ..
  - make all
  - make test_memcheck
  - tail -n +1 $(ls -v "${TRAVIS_BUILD_DIR}"/build/Testing/Temporary/MemoryChecker.*.log)
  - bash "${TRAVIS_BUILD_DIR}"/deploy.sh

notifications:
  email: false

env:
  global:
    - secure: "anSCBLe4pE47oRDYOEo9CMln5dp5oQmxoOybGYlMgqOkfhHEKlmAZoLH9vAnNWuYwa304FJTPVeCucu/LIac1biMNzvW4s3ITXYdXTmDi7yQpoUUTAquWa6/LVUkA50seokVWv811lNHjCio/Q4DIDRV5kx6e5iK1xNxOEi7PeAX0PaWwocs+ElcFY+jRkhf1NT5OA4wWwnn0aDdiUmCpkx5+88lXoke+EswcSkxAWE8d4c2EB/NqywvFM3tmDU1KFajWJEYXM+FkdeAHB+rG7RhFPH4rqac2fwHb2ubEkuSm260aHkKdSNk3DqGFdhXbUQaeyuE8J5IYjpPkFfL+UDIBphoG+hHLVJGvfnVTLx/OYlcgVLtBzNtLqW51bohIRFPS7D/+MdL+PAy8Ux0JqWd+ix9Pr6dbCZxnbglailU3wlsPNS4rf66wSXkbJ5XFCOyVa+sD1euqWpcKN3M7XbqKDGvtaGbGERH4v3lJTfruhLZ0MYedHpDqAlOdNQbzHXj4uHIWLAPe8pwhcWcnuo9EFbJ/m7t11feEXk6J1Up+/gvL8RF0yZhIqDc6KNJWvzC/Gzd3Va2d8LVLSPsmf+Tvg3lY+OMPhOY7JelLDmUiii/ZWScP7FRZJMGbiqBW0S1fsbkHomuy2zYjqi+nF9+Q6+AlPVcweKxgQFlNYw="
