language: cpp

matrix:
  include:
    - os: linux
      compiler:
        - g++
      addons:
        apt:
          packages:
            - liblua5.2-dev
            - python3-pytest

    - os: linux
      compiler:
        - g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - liblua5.2-dev
            - python3-pytest
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      compiler:
        - g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - liblua5.2-dev
            - python3-pytest
      env:
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      compiler:
        - g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - liblua5.2-dev
            - python3-pytest
            - doxygen
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - sudo add-apt-repository -y ppa:mhier/libboost-latest
  - sudo apt-get -q update
  - sudo apt-get -y install libboost1.70-dev
  - eval "${MATRIX_EVAL}"

script:
  - mkdir debug
  - cd debug
  - cmake -DCMAKE_BUILD_TYPE=Debug -DPYTHON_BINDINGS=ON -DPYTHON_EXECUTABLE=$(which python3) ..
  - make all
  - make test

after_success:
  - bash "${TRAVIS_BUILD_DIR}/deploy.sh"

notifications:
  email: false
