language: cpp

matrix:
  include:
    #- os: linux
    #  compiler:
    #    - g++
    #  addons:
    #    apt:
    #      sources:
    #        - boost-latest
    #      packages:
    #        - libboost-dev
    #        - libboost-graph-dev
    #        - liblua5.2-dev

    #- os: linux
    #  compiler:
    #    - g++
    #  addons:
    #    apt:
    #      sources:
    #        - ubuntu-toolchain-r-test
    #        - boost-latest
    #      packages:
    #        - g++-5
    #        - libboost-dev
    #        - libboost-graph-dev
    #        - liblua5.2-dev
    #  env:
    #     - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    #- os: linux
    #  compiler:
    #    - g++
    #  addons:
    #    apt:
    #      sources:
    #        - ubuntu-toolchain-r-test
    #        - boost-latest
    #      packages:
    #        - g++-6
    #        - libboost-dev
    #        - libboost-graph-dev
    #        - liblua5.2-dev
    #  env:
    #     - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      compiler:
        - g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - g++-7
            - libboost-dev
            - libboost-graph-dev
            - liblua5.2-dev
            - doxygen
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - cd debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make all
  - make test

after_success:
  - bash "${TRAVIS_BUILD_DIR}/deploy.sh"

notifications:
  email: false
