language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler:
        - g++
      addons:
        apt:
          packages:
            - liblua5.2-dev
            - python3-pytest
            - valgrind

    - os: linux
      dist: bionic
      compiler:
        - g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - liblua5.2-dev
            - python3-pytest
            - valgrind
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      dist: bionic
      compiler:
        - g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - liblua5.2-dev
            - python3-pytest
            - valgrind
      env:
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      dist: bionic
      compiler:
        - g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - liblua5.2-dev
            - python3-pytest
            - valgrind
            - doxygen
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
         - DEPLOY=Yes

before_install:
  - sudo add-apt-repository -y ppa:mhier/libboost-latest
  - sudo apt-get -q update
  - sudo apt-get -y install libboost1.70-dev
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DPYTHON_BINDINGS=ON -DPYTHON_EXECUTABLE=$(which python3) ..
  - make all
  - make test_memcheck
  - tail -n +1 $(ls -v "${TRAVIS_BUILD_DIR}"/build/Testing/Temporary/MemoryChecker.*.log)
  - bash "${TRAVIS_BUILD_DIR}"/deploy.sh

notifications:
  email: false
